rmdir /s /q "dist"
del "Snu Clipboard Manager Installer v0.9.exe"
python -m PyInstaller -w "Snu Clipboard Manager.spec"
del "dist\Snu Clipboard Manager\libgstreamer-1.0-0.dll"
del "dist\Snu Clipboard Manager\libglib-2.0-0.dll"
del "dist\Snu Clipboard Manager\libcrypto-1_1.dll"
del "dist\Snu Clipboard Manager\libgobject-2.0-0.dll"
del "dist\Snu Clipboard Manager\ucrtbase.dll"
del "dist\Snu Clipboard Manager\mfc140u.dll"
del "dist\Snu Clipboard Manager\libvorbis-0.dll"
del "dist\Snu Clipboard Manager\libogg-0.dll"
del "dist\Snu Clipboard Manager\libvorbisfile-3.dll"
del "dist\Snu Clipboard Manager\SDL2_mixer.dll"
del "dist\Snu Clipboard Manager\libmpg123-0.dll"
del "dist\Snu Clipboard Manager\libmodplug-1.dll"
del "dist\Snu Clipboard Manager\libFLAC-8.dll"
del "dist\Snu Clipboard Manager\libssl-1_1.dll"
del "dist\Snu Clipboard Manager\libtiff-5.dll"
del "dist\Snu Clipboard Manager\libwebp-7.dll"
del "dist\Snu Clipboard Manager\libffi-7.dll"
del "dist\Snu Clipboard Manager\libjpeg-9.dll"
del "dist\Snu Clipboard Manager\libgmodule-2.0-0.dll"
del "dist\Snu Clipboard Manager\libwinpthread-1.dll"
del "dist\Snu Clipboard Manager\libintl-8.dll"
del "dist\Snu Clipboard Manager\_elementtree.pyd"
del "dist\Snu Clipboard Manager\_lzma.pyd"
del "dist\Snu Clipboard Manager\_decimal.pyd"
del "dist\Snu Clipboard Manager\_ssl.pyd"
del "dist\Snu Clipboard Manager\_bz2.pyd"
del "dist\Snu Clipboard Manager\_hashlib.pyd"
del "dist\Snu Clipboard Manager\_multiprocessing.pyd"
del "dist\Snu Clipboard Manager\kivy_install\data\fonts\DejaVuSans.ttf"
del "dist\Snu Clipboard Manager\kivy_install\modules\_webdebugger.py"
rmdir /s /q "dist\Snu clipboard Manager\kivy_install\modules\__pycache__"
del "dist\Snu Clipboard Manager\api-ms-win-*.dll"
del "dist\Snu Clipboard Manager\LICENSE.*.txt"
rmdir /s /q "build"
xcopy "installer.nsi" "dist\Snu Clipboard Manager\"
"C:\Program Files (x86)\NSIS\makensis.exe" "dist\Snu Clipboard Manager\installer.nsi"
move "dist\Snu Clipboard Manager\Snu Clipboard Manager Installer v0.9.exe" .
cmd /k